[workspace]
resolver = "3"
members = ["crates/provider", "crates/domain/*"]

[workspace.dependencies]
hmac = "0.12"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[profile.dev]
opt-level = 1
debug = "line-tables-only"
debug-assertions = true
overflow-checks = true
incremental = true
lto = false
codegen-units = 256
panic = "unwind"

[profile.dev.package."*"]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
debug = "line-tables-only"
debug-assertions = false
overflow-checks = false
incremental = false
lto = "thin"
codegen-units = 8
panic = "unwind"
strip = "none"

[profile.dist]
inherits = "release"
opt-level = 3
debug = "line-tables-only"
lto = "thin"
codegen-units = 1
incremental = false
panic = "unwind"
strip = "none"
