[package]
name = "provider"
version = "0.1.0"
edition = "2024"

[features]
default = ["codex"]
anthropic = ["dep:provider-anthropic"]
civitai = ["dep:provider-civitai"]
codex = ["dep:provider-codex"]
deepseek = ["dep:provider-deepseek"]
exa = ["dep:provider-exa"]
openai = ["dep:provider-openai"]
siliconflow = ["dep:provider-siliconflow"]
volcengine = ["dep:provider-volcengine"]

[dependencies]
provider-anthropic = { path = "../domain/anthropic", optional = true }
provider-civitai = { path = "../domain/civitai", optional = true }
provider-codex = { path = "../domain/codex", optional = true }
provider-deepseek = { path = "../domain/deepseek", optional = true }
provider-exa = { path = "../domain/exa", optional = true }
provider-openai = { path = "../domain/openai", optional = true }
provider-siliconflow = { path = "../domain/siliconflow", optional = true }
provider-volcengine = { path = "../domain/volcengine", optional = true }
